### ISSUE TITLE
Spurious message box when switching to encrytped profile

### ISSUE THREAD

**Issue by tux3** [dubslow/qTox#3]
When switching to an encrypted profile, the following message box appears, but the profile is still decrypted correctly, and encryption stays on.

![image](https://cloud.githubusercontent.com/assets/5155966/5881789/e085d4fc-a343-11e4-828d-7dfa7cc00039.jpg)

Repro:
- Create an encrypted account and an unencrypted one.
- Switch to the unencrypted profile
- Try to switch back, the message box pictured above opens before the password prompt

**Comment by dubslow** [comment]
zetok reported a similar issue, but I was unable to reproduce, and he fixed it by manually editing the unencrypted profile's `.ini` to have the setting set to false. This bad state was caused by older buggier versions, and the current version doesn't write the change in settings I guess. At any rate, with non-testing clients, it shouldn't be an issue. (I wasn't able to reproduce myself just now, to be sure.)
