### ISSUE TITLE
Disabling an encrypted history deletes/corrupts it

### ISSUE THREAD

**Issue by tux3** [dubslow/qTox#6]
Clicking the "disable history" button and then trying to enable it again results in a corrupted and lost history.

Repro :
- Have an encrypted profile & history
- Restart, enter you profile password
- Click disable history at the history password prompt
- Enable encrypted history again in settings (with any password, same or not)
- History gets corrupted with "EncryptedDb::pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted" in log
- History can be used again, but the old history is lost without any confirmation

**Comment by dubslow** [comment]
Disable history has so far implicitly meant delete history, I guess I'll have to be pickier on handling it

**Comment by tux3** [comment]
Also causes issues if disabled via the checkbox and re-enabled after restart.

The following chat box pops up, since the history is corrupted (not just deleted) :

![image4](https://cloud.githubusercontent.com/assets/5155966/5882373/2db4e646-a349-11e4-8c16-cbe7e873c42a.jpg)

**Comment by dubslow** [comment]
I read the code closer and discovered/recalled that these two issues are the same; the dialog in question treats all values that aren't `Accept` the same, i.e. `Disable history` and otherwise closing the dialog result in the same code execution.

Not being able to see anything in particular in the code that actually causes problems, and not having access to being able to debug it myself, I'd like you to try this. It's possible that changing the `Settings` value was never being propagated to the history code, which this is intended to fix. (If this doesn't fix it, then obviously that hypothesis isn't true.)

**Comment by tux3** [comment]
With this patch, the message box does not pop up anymore, and can be used again after being re-activated.

That said, the following messages do appear in the log when disabling hisotyr encryption :
<blockquote>
Core: Connected to DHT
Core: writing tox_save to  "/home/mlkj/.config/tox/Tux3.tox"
Settings: Saving in  "/home/mlkj/.config/tox/qtox.ini"
HistoryKeeper: count 0 messages exported
EncryptedDb::pullFileContent: got chunk: 4096
Core::decryptData: decryption failed
EncryptedDb::pullFileContent: Encrypted history log is corrupted: can't decrypt, will be deleted
</blockquote>
I don't know whether this means that there is still a problem (the messages seem to imply that we're trying to keep decrypted history, not just delete it, and failed), but this issue in particular seems fixed.

**Comment by dubslow** [comment]
What happens if you actually have a history to be decrypted?

**Comment by tux3** [comment]
If I have an encrypted history and disable it on start via the dialog box, no message appear in the log, the history is deleted, and the checkboxes are unchecked in the options.

**Comment by dubslow** [comment]
That's the other issue, right?

What I meant was, the log above said that there were zero messages actually recorded in history, which may have been the source of the error logs. So just type something to groupbot and try again.

**Comment by tux3** [comment]
There were zero messages since the history was deleted when it was disabled.

I sent a couple messages to audiobot with encrypted history. Those were stored correctly.
Then I restarted, disabled encrypted history and the history got deleted. No messages to audiobot anymore.
Then I enabled encrypted history again and those messages popup up in the log.
Disabling history deletes it, thus there are zero messages when you try to enable it again.

If I disable history (thus deleting it), then enable unencrypted history and send some messages, then enable encrypted history again, I get
>HistoryKeeper: count 10 messages exported
>EncryptedDb::pullFileContent: file doesn't exist

**Comment by dubslow** [comment]
Ah okay (I think, my mind is turning into logical spaghetti right now).

So both #5 and #6 as originally posted (and since they are the same problem) are still an issue, but this fixed the second comment here. At the moment at least, I don't think I can do much troubleshooting, I've been thinking about this far too long, and like I said, I'm only going to confuse myself the rest of the evening. You can take a whack at it with a debugger if you want :) by I certainly don't expect you to lol.

**Comment by tux3** [comment]
It's alright :)

I might just take a look at it tomorrow if I have time, but no promises.
